#!/usr/bin/env bash
set -euo pipefail

repository_root=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$repository_root"

private_pattern='(/Users/[^/]+/|Obsidian|\.codex/|rollout_path|Areas/Engineering|private[- ]vault)'
attribution_pattern='(Co-authored-by:|Generated with|generated by (AI|an? (agent|assistant)))'

if git grep -n -I -E "$private_pattern" HEAD -- . \
  ':(exclude)scripts/check-public.sh'; then
  echo "public-boundary check found a private planning or local-path reference" >&2
  exit 1
fi

while IFS= read -r commit; do
  if git grep -n -I -E "$private_pattern" "$commit" -- . \
    ':(exclude)scripts/check-public.sh'; then
    echo "public-boundary check found a private reference in reachable commit $commit" >&2
    exit 1
  fi
done < <(git rev-list HEAD)

if git log HEAD --format='%H%n%B%x00' | grep -a -E -i "$private_pattern|$attribution_pattern"; then
  echo "public-boundary check found private context or attribution in commit history" >&2
  exit 1
fi

if git status --porcelain | grep -q .; then
  echo "public-boundary check requires a clean worktree" >&2
  exit 1
fi

echo "Public tree and reachable history contain no private references or attribution."
